version: '3.8'
services:
    wordpress:
        image: wordpress
        container_name: wordpress_8999
        links:
            - mariadb:mysql
        environment:
            - WORDPRESS_DB_PASSWORD=password
            - WORDPRESS_DB_USER=root
        ports:
            - "8999:80"
        volumes:
            - ./html:/var/www/html
    mariadb:
        image: mariadb:latest
        container_name: mariadb_3669
        restart: always
        ports: 
            - "3669:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=wordpress
        volumes:
            - ./database:/var/lib/mysql